/**
 * @file font.h
 * @brief Generic packed 1-bit bitmap-font definitions.
 *
 * This file was generated by bitmap_font_generator.py.
 */

#ifndef FONT_H
#define FONT_H

#include <stdint.h>

/**
 * @brief Description of a single glyph.
 *
 * offsetX and offsetY are relative to the text pen's baseline position.
 * A glyph pixel at local coordinate (x, y) is drawn at:
 *
 *     screenX = penX + offsetX + x
 *     screenY = baselineY + offsetY + y
 */
typedef struct
{
    uint32_t bitmapOffset;

    uint8_t width;
    uint8_t height;
    uint8_t advance;

    int8_t offsetX;
    int8_t offsetY;
} FontGlyph;

/**
 * @brief Description of a packed 1-bit bitmap font.
 *
 * Each glyph begins at a byte boundary. Within a glyph, pixels are packed
 * left-to-right and top-to-bottom, most-significant bit first.
 */
typedef struct
{
    const uint8_t *bitmap;
    const FontGlyph *glyphs;

    uint32_t firstCodepoint;
    uint16_t glyphCount;

    uint8_t nominalSize;
    uint8_t lineHeight;
    uint8_t ascent;
    uint8_t descent;
} Font;

#endif /* FONT_H */
