/**
 * @file open_sans.h
 * @brief Generated OpenSans packed 1-bit bitmap fonts.
 *
 * This file was generated by bitmap_font_generator.py.
 */

#ifndef OPEN_SANS_H
#define OPEN_SANS_H

#include "font.h"

extern const Font OpenSans12;
extern const Font OpenSans16;
extern const Font OpenSans20;
extern const Font OpenSans28;
extern const Font OpenSans36;

#endif /* OPEN_SANS_H */
