#!/usr/bin/env python3
"""
instrument_converter.py

Convert a single-note WAV recording into a DualSlide music instrument.

Output (in software/assets/instruments by default):
    <name>.h    declares   extern const Music_InstrumentTypeDef Instrument_<Name>;
    <name>.c    contains   the 24 kHz mono 16-bit samples and the instrument

Requirements:
    python -m pip install numpy scipy

Usage:
    python instrument_converter.py piano.wav --root C5
    python instrument_converter.py strings.wav --name strings --root A4 --loop 0.120 0.380 --release-ms 250

    --root      Note the recording plays at: a MIDI number (60) or a note name.
                Names use FL Studio octave numbering, where middle C is C5;
                pass --standard-octaves if your names use C4 for middle C.
    --loop      Loop region in seconds. A held note repeats this region until
                it is released, so the recording can be short. Loop points are
                moved to the nearest rising zero crossing unless --no-snap is
                given. Without --loop the note plays to the end of the file.
    --release-ms  Fade-out time after a note ends (default 100 ms).
    --normalize Scale the recording so its peak is just below full scale.

Export the WAV from FL Studio as a single held note; any sample rate, bit
depth, and channel count is accepted and converted to 24 kHz mono.
"""

from __future__ import annotations

import argparse
import re
import sys
from math import gcd
from pathlib import Path

try:
    import numpy as np
    from scipy.io import wavfile
    from scipy.signal import resample_poly
except ImportError as exc:
    sys.exit(f"Missing dependency ({exc.name}). Install with: python -m pip install numpy scipy")

SAMPLE_RATE_HZ = 24000
NORMALIZE_PEAK = 0.98
ZERO_CROSSING_SEARCH_SECONDS = 0.002
NOTE_NAMES = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}
DEFAULT_OUTPUT = Path(__file__).resolve().parents[2] / "assets" / "instruments"


def parse_note(text: str, standard_octaves: bool) -> int:
    """Return the MIDI note number for '60', 'C5', 'F#4', or 'Bb3'."""
    if text.isdigit():
        note = int(text)
    else:
        match = re.fullmatch(r"([A-Ga-g])([#b]?)(-?\d+)", text.strip())
        if not match:
            raise argparse.ArgumentTypeError(f"invalid note '{text}'")
        letter, accidental, octave = match.groups()
        note = NOTE_NAMES[letter.upper()] + {"#": 1, "b": -1, "": 0}[accidental]
        note += (int(octave) + 1) * 12 if standard_octaves else int(octave) * 12
    if not 0 <= note <= 127:
        raise argparse.ArgumentTypeError(f"note '{text}' is outside MIDI range 0-127")
    return note


def pascal_case(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", name) if part)


def load_mono(path: Path) -> tuple[np.ndarray, int]:
    """Load a WAV file as float samples in -1..1, averaging all channels."""
    rate, data = wavfile.read(path)
    if data.dtype == np.uint8:
        samples = (data.astype(np.float64) - 128.0) / 128.0
    elif np.issubdtype(data.dtype, np.integer):
        samples = data.astype(np.float64) / float(np.iinfo(data.dtype).max)
    else:
        samples = data.astype(np.float64)
    if samples.ndim > 1:
        samples = samples.mean(axis=1)
    return samples, rate


def resample(samples: np.ndarray, rate: int) -> np.ndarray:
    if rate == SAMPLE_RATE_HZ:
        return samples
    divisor = gcd(SAMPLE_RATE_HZ, rate)
    return resample_poly(samples, SAMPLE_RATE_HZ // divisor, rate // divisor)


def snap_to_zero_crossing(samples: np.ndarray, index: int) -> int:
    """Move index to the nearest rising zero crossing within a few milliseconds."""
    radius = int(ZERO_CROSSING_SEARCH_SECONDS * SAMPLE_RATE_HZ)
    low = max(1, index - radius)
    high = min(len(samples) - 1, index + radius)
    crossings = [i for i in range(low, high + 1) if samples[i - 1] < 0.0 <= samples[i]]
    return min(crossings, key=lambda i: abs(i - index)) if crossings else index


def write_files(output: Path, name: str, samples: np.ndarray, loop: tuple[int, int], root: int, release_ms: int) -> None:
    symbol = "Instrument_" + pascal_case(name)
    guard = "INSTRUMENT_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper() + "_H"
    values = np.clip(np.round(samples * 32767.0), -32768, 32767).astype(np.int16)

    header = (
        "/**\n"
        f" * @file {name}.h\n"
        f" * @brief {pascal_case(name)} music instrument.\n"
        " *\n"
        " * Generated by tools/music_converter/instrument_converter.py; do not edit.\n"
        " */\n\n"
        f"#ifndef {guard}\n#define {guard}\n\n"
        '#include "music.h"\n\n'
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        f"extern const Music_InstrumentTypeDef {symbol};\n\n"
        "#ifdef __cplusplus\n}\n#endif\n\n"
        f"#endif /* {guard} */\n"
    )

    rows = []
    for start in range(0, len(values), 12):
        rows.append("    " + ", ".join(str(int(v)) for v in values[start:start + 12]))
    source = (
        "/**\n"
        f" * @file {name}.c\n"
        f" * @brief {pascal_case(name)} music instrument data.\n"
        " *\n"
        " * Generated by tools/music_converter/instrument_converter.py; do not edit.\n"
        " */\n\n"
        f'#include "{name}.h"\n\n'
        f"static const Audio_SampleTypeDef {symbol}Samples[{len(values)}] =\n{{\n"
        + ",\n".join(rows)
        + "\n};\n\n"
        f"const Music_InstrumentTypeDef {symbol} =\n{{\n"
        f"    .Samples = {symbol}Samples,\n"
        f"    .SampleCount = {len(values)}U,\n"
        f"    .LoopStart = {loop[0]}U,\n"
        f"    .LoopEnd = {loop[1]}U,\n"
        f"    .ReleaseMilliseconds = {release_ms}U,\n"
        f"    .RootNote = {root}U\n"
        "};\n"
    )

    output.mkdir(parents=True, exist_ok=True)
    (output / f"{name}.h").write_text(header, encoding="utf-8", newline="\r\n")
    (output / f"{name}.c").write_text(source, encoding="utf-8", newline="\r\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("wav", type=Path, help="single-note WAV recording")
    parser.add_argument("--name", help="instrument name and file name (default: WAV file name)")
    parser.add_argument("--root", required=True, help="note the recording plays at (MIDI number or name)")
    parser.add_argument("--standard-octaves", action="store_true", help="note names use C4 for middle C")
    parser.add_argument("--loop", nargs=2, type=float, metavar=("START", "END"), help="loop region in seconds")
    parser.add_argument("--no-snap", action="store_true", help="keep loop points exactly where given")
    parser.add_argument("--release-ms", type=int, default=100, help="fade-out after a note ends (default 100)")
    parser.add_argument("--normalize", action="store_true", help="scale the peak to just below full scale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="output folder")
    args = parser.parse_args()

    name = re.sub(r"[^A-Za-z0-9_]", "_", args.name or args.wav.stem).lower()
    root = parse_note(args.root, args.standard_octaves)
    if not 0 <= args.release_ms <= 65535:
        sys.exit("--release-ms must be between 0 and 65535")

    samples, rate = load_mono(args.wav)
    samples = resample(samples, rate)

    peak = float(np.max(np.abs(samples))) if len(samples) else 0.0
    if args.normalize and peak > 0.0:
        samples = samples * (NORMALIZE_PEAK / peak)
    elif peak > 1.0:
        print(f"warning: peak {peak:.2f} exceeds full scale and will clip; consider --normalize")

    loop = (0, 0)
    if args.loop:
        start = int(round(args.loop[0] * SAMPLE_RATE_HZ))
        end = int(round(args.loop[1] * SAMPLE_RATE_HZ))
        if not 0 <= start < end <= len(samples):
            sys.exit(f"loop must satisfy 0 <= START < END <= {len(samples) / SAMPLE_RATE_HZ:.3f} s")
        if not args.no_snap:
            start = snap_to_zero_crossing(samples, start)
            end = snap_to_zero_crossing(samples, end)
        if end - start < 2:
            sys.exit("loop region is too short after snapping; try --no-snap or a longer loop")
        samples = samples[:end]
        loop = (start, end)

    write_files(args.output, name, samples, loop, root, args.release_ms)

    seconds = len(samples) / SAMPLE_RATE_HZ
    looping = f", loop {loop[0]}-{loop[1]}" if loop[1] else ", plays to end"
    print(f"{name}: root {root}, {len(samples)} samples ({seconds:.3f} s, {len(samples) * 2} bytes){looping}")
    print(f"wrote {args.output / (name + '.h')} and {args.output / (name + '.c')}")


if __name__ == "__main__":
    main()
